### ISSUE TITLE
[QUESTION] 安装时无法删除 Installer 文件夹

### ISSUE THREAD

**Issue by WangNingkai** [hyperf-cloud/hyperf-skeleton#10]
执行此命令
`composer create-project hyperf/hyperf-skeleton`
会报如下错误

![image](https://user-images.githubusercontent.com/23030927/62943899-1acd6a00-be0e-11e9-82fd-e9f46456e70d.png)

**Comment by huangzhhui** [comment]
请提供你的环境信息

**Comment by WangNingkai** [comment]
@huangzhhui 
系统：centos7 
PHP环境：PHP 7.3.8  已安装最新 swoole4.4.3
目录权限：777

**Comment by huangzhhui** [comment]
多次执行都是这样吗？

**Comment by WangNingkai** [comment]
之前安装了多次，时断时续都会出现此问题。刚才又试了下，此次我手动删除目录后执行 `composer install` ，提示我关闭swoole短别名，关闭后就可以正常运行了，然后再次安装就不会报错了，可能是短别名的问题导致的。感谢解答，应该是我的问题，文档没有看完整！！希望越来越好
